language: bash

sudo: required

addons:
    apt:
        packages:
        - tree

before_script:
    - mkdir testHome
    - export HOME="$PWD/testHome"

script:
    - yes y | bash -c "$(wget -qO - https://raw.github.com/harshilpatel312/dotfiles/master/install.sh)"

after_script:
    - tree -a -I .git $HOME
